name: Deploy Metadata to Target Org

on:
  push:
    branches:
      - main  # Triggers on push to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install Salesforce CLI
      run: |
        npm install -g @salesforce/cli
        sf --version

    - name: Authenticate Source Org
      run: |
          response=$(curl -X POST "https://login.salesforce.com/services/oauth2/token" \
            -d "grant_type=password" \
            -d "client_id=${{ secrets.SF_CLIENT_ID_SOURCE }}" \
            -d "client_secret=${{ secrets.SF_CLIENT_SECRET_SOURCE }}" \
            -d "username=${{ secrets.SF_USERNAME_SOURCE }}" \
            -d "password=${{ secrets.SF_PASSWORD }}" )
  
          SF_ACCESS_TOKEN=$(echo "$response" | jq -r '.access_token')
  
          if [ -z "$SF_ACCESS_TOKEN" ]; then
            echo "Salesforce authentication failed."
            exit 1
          fi
  
          echo "SF_ACCESS_TOKEN=$SF_ACCESS_TOKEN" >> $GITHUB_ENV
          echo "Successfully authenticated with Salesforce."

    - name: Authenticate Target Org
      run: |
            response=$(curl -X POST "https://login.salesforce.com/services/oauth2/token" \
              -d "grant_type=password" \
              -d "client_id=${{ secrets.SF_CLIENT_ID_TARGET }}" \
              -d "client_secret=${{ secrets.SF_CLIENT_SECRET_TARGET }}" \
              -d "username=${{ secrets.SF_USERNAME_TARGET }}" \
              -d "password=${{ secrets.SF_PASSWORD_TARGET }}" )
    
            SF_ACCESS_TOKEN=$(echo "$response" | jq -r '.access_token')
    
            if [ -z "$SF_ACCESS_TOKEN" ]; then
              echo "Salesforce authentication failed."
              exit 1
            fi
    
            echo "SF_ACCESS_TOKEN=$SF_ACCESS_TOKEN" >> $GITHUB_ENV
            echo "Successfully authenticated with Salesforce."
  

    - name: Retrieve Metadata from Source Org
      run: |
        mkdir mdapi_source
        sf project retrieve start --metadata ApexClass,ApexTrigger --target-org sourceOrg --output-dir mdapi_source

    - name: Deploy Metadata to Target Org
      run: |
        sf project deploy start --metadata-dir mdapi_source --target-org targetOrg --wait 10 --test-level NoTestRun
