name: Salesforce Code Analyzer CSV Scan

on:
  push:
    branches:
      - "**"

permissions:
  contents: write

jobs:
  static-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Salesforce Code Analyzer as local module
        run: npm install --save-dev @salesforce/code-analyzer@5.1.0

      - name: Run Code Analyzer and export to CSV
        run: |
          npx sf code-analyzer run \
            --workspace "force-app/main/default/classes/Demo.cls" \
            --rule-selector AvoidDebugStatements \
            --output-format csv \
            --output-file scanner-report.csv \
            --config-file code-analyzer.yml

      - name: Upload Scanner Report CSV
        uses: actions/upload-artifact@v4
        with:
          name: code-analyzer-report
          path: scanner-report.csv
