name: Salesforce Code Analyzer v5 Scan

on:
  push:
    branches:
      - "**"

permissions:
  contents: write

jobs:
  static-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Salesforce CLI
        run: npm install --global @salesforce/cli

      - name: Disable Auto Plugin Auto-Install
        run: |
          mkdir -p ~/.sf
          echo '{"plugins":{"autoInstall":false}}' > ~/.sf/sf-config.json

      - name: Uninstall legacy scanner if present
        run: sf plugins uninstall @salesforce/sfdx-scanner || true

      - name: Install Code Analyzer Plugin v5.0.0
        run: sf plugins install @salesforce/plugin-code-analyzer@5.0.0

      - name: Confirm Installed Plugin
        run: sf plugins list

      - name: Run Salesforce Code Analyzer v5 - CSV Output
        run: |
          sf code-analyzer run \
            --workspace "force-app/main/default/classes/Demo.cls" \
            --rule-selector AvoidDebugStatements \
            --output-format csv \
            --output-file scanner-report.csv \
            --config-file code-analyzer.yml

      - name: Upload Scanner Report CSV
        uses: actions/upload-artifact@v4
        with:
          name: code-analyzer-report
          path: scanner-report.csv
