name: Salesforce Code Analyzer v5

on:
  push:
    branches:
      - "**"

permissions:
  contents: write

jobs:
  static-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Salesforce CLI
        run: npm install --global @salesforce/cli

      - name: Disable Auto Plugin Auto-Install
        run: |
          mkdir -p ~/.sf
          echo '{"plugins":{"autoInstall":false}}' > ~/.sf/sf-config.json

      - name: Uninstall conflicting plugins
        run: |
          sf plugins uninstall @salesforce/sfdx-scanner || true
          sf plugins uninstall @salesforce/plugin-code-analyzer || true

      - name: Install Code Analyzer Plugin v5.0.0
        run: sf plugins install @salesforce/plugin-code-analyzer@5.0.0

      - name: Confirm Installed Plugins
        run: sf plugins

      - name: Run Salesforce Code Analyzer - Output JSON
        run: |
          sf code-analyzer run \
            --workspace "force-app\main\default\classes\Demo.cls" \
            --rule-selector AvoidDebugStatements \
            --output-file scanner-report.json \
            --config-file code-analyzer.yml

      - name: Convert JSON report to CSV
        run: |
          cat > convert.js << 'EOF'
          const fs = require('fs');
          const jsonPath = 'scanner-report.json';

          if (!fs.existsSync(jsonPath)) {
            console.error('scanner-report.json not found.');
            process.exit(1);
          }

          const report = JSON.parse(fs.readFileSync(jsonPath, 'utf8'));

          const allResults = [];
          if (report.results && typeof report.results === 'object') {
            for (const engine in report.results) {
              const violations = report.results[engine];
              if (Array.isArray(violations)) {
                allResults.push(...violations);
              }
            }
          }

          if (allResults.length === 0) {
            console.warn('No violations found.');
            fs.writeFileSync('scanner-report.csv', 'fileName,line,column,ruleName,severity,message\n');
            process.exit(0);
          }

          const headers = ["fileName", "line", "column", "ruleName", "severity", "message"];
          const rows = allResults.map(r => [
            r.fileName, r.line, r.column, r.ruleName, r.severity, `"${(r.message || '').replace(/"/g, '""')}"`
          ]);
          const csv = [headers.join(','), ...rows.map(r => r.join(','))].join('\n');
          fs.writeFileSync('scanner-report.csv', csv);
          EOF

          node convert.js

      - name: Upload Scanner Report CSV
        uses: actions/upload-artifact@v4
        with:
          name: code-analyzer-report
          path: scanner-report.csv
